import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _kLocaleStorageKey = '__locale_key__';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations)!;

  static List<String> languages() =>
      ['en', 'ar', 'ur', 'hi', 'bn', 'tr', 'ru', 'fr', 'es', 'id', 'ms', 'fa'];

  static late SharedPreferences _prefs;
  static Future initialize() async =>
      _prefs = await SharedPreferences.getInstance();
  static Future storeLocale(String locale) =>
      _prefs.setString(_kLocaleStorageKey, locale);
  static Locale? getStoredLocale() {
    final locale = _prefs.getString(_kLocaleStorageKey);
    return locale != null && locale.isNotEmpty ? createLocale(locale) : null;
  }

  String get languageCode => locale.toString();
  String? get languageShortCode =>
      _languagesWithShortCode.contains(locale.toString())
          ? '${locale.toString()}_short'
          : null;
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key) =>
      (kTranslationsMap[key] ?? {})[locale.toString()] ?? '';

  String getVariableText({
    String? enText = '',
    String? arText = '',
    String? urText = '',
    String? hiText = '',
    String? bnText = '',
    String? trText = '',
    String? ruText = '',
    String? frText = '',
    String? esText = '',
    String? idText = '',
    String? msText = '',
    String? faText = '',
  }) =>
      [
        enText,
        arText,
        urText,
        hiText,
        bnText,
        trText,
        ruText,
        frText,
        esText,
        idText,
        msText,
        faText
      ][languageIndex] ??
      '';

  static const Set<String> _languagesWithShortCode = {
    'ar',
    'az',
    'ca',
    'cs',
    'da',
    'de',
    'dv',
    'en',
    'es',
    'et',
    'fi',
    'fr',
    'gr',
    'he',
    'hi',
    'hu',
    'it',
    'km',
    'ku',
    'mn',
    'ms',
    'no',
    'pt',
    'ro',
    'ru',
    'rw',
    'sv',
    'th',
    'uk',
    'vi',
  };
}

/// Used if the locale is not supported by GlobalMaterialLocalizations.
class FallbackMaterialLocalizationDelegate
    extends LocalizationsDelegate<MaterialLocalizations> {
  const FallbackMaterialLocalizationDelegate();

  @override
  bool isSupported(Locale locale) => _isSupportedLocale(locale);

  @override
  Future<MaterialLocalizations> load(Locale locale) async =>
      SynchronousFuture<MaterialLocalizations>(
        const DefaultMaterialLocalizations(),
      );

  @override
  bool shouldReload(FallbackMaterialLocalizationDelegate old) => false;
}

/// Used if the locale is not supported by GlobalCupertinoLocalizations.
class FallbackCupertinoLocalizationDelegate
    extends LocalizationsDelegate<CupertinoLocalizations> {
  const FallbackCupertinoLocalizationDelegate();

  @override
  bool isSupported(Locale locale) => _isSupportedLocale(locale);

  @override
  Future<CupertinoLocalizations> load(Locale locale) =>
      SynchronousFuture<CupertinoLocalizations>(
        const DefaultCupertinoLocalizations(),
      );

  @override
  bool shouldReload(FallbackCupertinoLocalizationDelegate old) => false;
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => _isSupportedLocale(locale);

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

Locale createLocale(String language) => language.contains('_')
    ? Locale.fromSubtags(
        languageCode: language.split('_').first,
        scriptCode: language.split('_').last,
      )
    : Locale(language);

bool _isSupportedLocale(Locale locale) {
  final language = locale.toString();
  return FFLocalizations.languages().contains(
    language.endsWith('_')
        ? language.substring(0, language.length - 1)
        : language,
  );
}

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // Entry
  {
    'kyvwzrp5': {
      'en': 'SCMCC',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '2ggd6ayb': {
      'en': 'Please fill the information below',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'ks9l4l73': {
      'en': 'Sign in with Google',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'yfablgwc': {
      'en': 'Sign in with Apple',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'dg5gyhb3': {
      'en': 'Sign in with Email',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '121q7qax': {
      'en': 'Enter as a Guest',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'shpsw24j': {
      'en': 'By creating an account, you agree to our ',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'ohkabwc0': {
      'en': 'Terms and Conditions',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'ge30j7wu': {
      'en': ' and ',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'dspuvh8s': {
      'en': 'EULA',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '6e24mkpd': {
      'en': 'Home',
      'ar': 'بيت',
      'bn': 'বাড়ি',
      'es': 'Hogar',
      'fa': 'صفحه اصلی',
      'fr': 'Maison',
      'hi': 'घर',
      'id': 'Rumah',
      'ms': 'Rumah',
      'ru': 'Дом',
      'tr': 'Ev',
      'ur': 'گھر',
    },
  },
  // Home
  {
    'or7lt7lc': {
      'en': 'Iqama Times',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'wkxax5wy': {
      'en': 'Fajr',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'byj5gjsa': {
      'en': 'Duhur',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '0kila3kh': {
      'en': 'Asr',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '75u3c5pb': {
      'en': 'Maghrib',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '7tee94gy': {
      'en': 'Isha',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'pzdv26cf': {
      'en': 'Jumaa',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '4ris13pw': {
      'en': 'Donate',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '42zxn9ut': {
      'en': 'Home',
      'ar': 'بيت',
      'bn': 'বাড়ি',
      'es': 'Hogar',
      'fa': 'صفحه اصلی',
      'fr': 'Maison',
      'hi': 'घर',
      'id': 'Rumah',
      'ms': 'Rumah',
      'ru': 'Дом',
      'tr': 'Ev',
      'ur': 'گھر',
    },
  },
  // CreateAccount
  {
    'ogniwg05': {
      'en': 'Create Profile',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'xlo578xa': {
      'en': 'Please fill in the below information',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'n4d9bcxy': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '1wfx38vc': {
      'en': 'Name',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '2g8797ca': {
      'en': 'Male',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'p2z3ya44': {
      'en': 'Female',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '0lknsi0c': {
      'en': 'Select your Gender',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'huqj4ovx': {
      'en': 'Search...',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '0pybzgr8': {
      'en': 'Continue',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'mm4rwye5': {
      'en': 'Home',
      'ar': 'بيت',
      'bn': 'বাড়ি',
      'es': 'Hogar',
      'fa': 'صفحه اصلی',
      'fr': 'Maison',
      'hi': 'घर',
      'id': 'Rumah',
      'ms': 'Rumah',
      'ru': 'Дом',
      'tr': 'Ev',
      'ur': 'گھر',
    },
  },
  // admin
  {
    'duz9eo4s': {
      'en': 'Control Centre',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'lct20sq2': {
      'en': 'Manage Prayer Times',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '9qljqtip': {
      'en': 'Manage Events',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'h2q9b2nv': {
      'en': 'Manage Announcements',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '76me2n7e': {
      'en': 'Manage Media',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'fdcfcyim': {
      'en': 'Manage Jobs',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'x4oodixw': {
      'en': 'Manage Resources',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '51skqoab': {
      'en': 'Home',
      'ar': 'بيت',
      'bn': 'বাড়ি',
      'es': 'Hogar',
      'fa': 'صفحه اصلی',
      'fr': 'Maison',
      'hi': 'घर',
      'id': 'Rumah',
      'ms': 'Rumah',
      'ru': 'Дом',
      'tr': 'Ev',
      'ur': 'گھر',
    },
  },
  // emailSignUp
  {
    '0oh898e9': {
      'en': 'Signing up with Email',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'ipnr9gmc': {
      'en': 'Sign Up',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'oayztqh1': {
      'en': 'Please fill the information below',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '86dljpal': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'cjv2b0u9': {
      'en': 'Email',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'xthstdco': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'qb25b0t3': {
      'en': 'Password',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'hzv31iqw': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'vebqonso': {
      'en': 'Confirm Password',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '20ctkdus': {
      'en': 'Create Account',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '0p5fyovx': {
      'en': 'Already have an account? ',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    's8pbx293': {
      'en': 'Log in',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'stgr9stj': {
      'en': 'Home',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
  },
  // emailLogin
  {
    'kzyh5j2t': {
      'en': 'Logging in with Email',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '1a6oigrk': {
      'en': 'Log In',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '3dazuk1f': {
      'en': 'Please fill the information below',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '3gsea397': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'g9o4kf50': {
      'en': 'Email',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'o82v2k5y': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'qgmhze4c': {
      'en': 'Password',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '0752rwoc': {
      'en': 'Log In',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'ielm05sm': {
      'en': 'Don\'t have an account yet? ',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'nqx3qia8': {
      'en': 'Sign up',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'sf22a2pg': {
      'en': 'Home',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
  },
  // forgotPassword
  {
    'i5eur05r': {
      'en': 'Back',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'ytaj8zn8': {
      'en': 'Forgot Password',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'zttm2etb': {
      'en':
          'We will send you an email with a link to reset your password, please enter the email associated with your account below.',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '71rlhkbf': {
      'en': 'Your email address...',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'exx6srzo': {
      'en': 'Enter your email...',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '6es6fdca': {
      'en': 'Send Link',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '8lyywakz': {
      'en': 'Home',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
  },
  // Welcome
  {
    'i3yqj96u': {
      'en': 'Peace Be Upon You',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'io4zex5p': {
      'en': 'السلام عليكم',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'kc55xytr': {
      'en': 'Continue',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '6u7xyfdc': {
      'en': 'Home',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
  },
  // Media
  {
    'pfltldoq': {
      'en': 'SCMCC',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'yydblgbm': {
      'en': 'SCMCC Media',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '7suvc5ou': {
      'en': 'Written resources',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '313opga3': {
      'en': 'Top 10',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '0kzbykzp': {
      'en': 'Latest Releases',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'xa6ln3qd': {
      'en': 'For Brothers',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'lspvvz6j': {
      'en': 'For Sisters',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'yskqvdy3': {
      'en': 'Home',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
  },
  // Jobs
  {
    'y3gkber2': {
      'en': 'SCMCC Volunteering',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '3nh8l9cd': {
      'en': 'Home',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
  },
  // Profile
  {
    'iz5lkgoh': {
      'en': 'Profile',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '1z7qlduy': {
      'en': 'Admin',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'd6ag3088': {
      'en': 'Edit Profile',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'wpbulrta': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'm1le267k': {
      'en': 'Name',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '9lye7mdm': {
      'en': 'Sign in',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'u6wykl3a': {
      'en': 'Contact Via Email',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'lynhrto5': {
      'en': 'Administrator Portal',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'm5qtrwnc': {
      'en': 'Contact Administrators',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'clqvi6pm': {
      'en': 'Home',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
  },
  // singleMedia
  {
    'k5e246z5': {
      'en': 'Media',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'zxvp66ff': {
      'en': 'Play',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'tmz37zkm': {
      'en': 'More like this',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'j4bvqsao': {
      'en': 'Episodes',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'vjns5zvk': {
      'en': 'Home',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
  },
  // singleJob
  {
    '5jw1tb21': {
      'en': 'Jobs',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '31j82r4z': {
      'en': 'Apply',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'zgre2d3g': {
      'en': 'You have Applied',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'gfma4nix': {
      'en': 'Warning: You have no Resume on File.',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '2ucjf698': {
      'en': 'Home',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
  },
  // announcements
  {
    'fw0sj86t': {
      'en': 'Announcements',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'dt7csv16': {
      'en': 'Home',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
  },
  // directory
  {
    'vpubh97m': {
      'en': 'Admin Directory',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'jy1k94i8': {
      'en': 'Users can contact you',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'xbl8s8y7': {
      'en': 'Users can not contact you',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'f7f6ecph': {
      'en': 'Home',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
  },
  // prayerTimes
  {
    'l0vqbv7o': {
      'en': 'Prayer Times',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '1pb3ah0j': {
      'en': 'Saved',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'oygcpgi6': {
      'en': 'First Jumaa',
      'ar': 'وقت صلاة الجمعة',
      'bn': 'জুমার নামাজের সময়',
      'es': 'Tiempo de oración de Jumaa',
      'fa': 'وقت نماز جمعه',
      'fr': 'Heure de prière à Joumaa',
      'hi': 'जुमा की नमाज का समय',
      'id': 'Waktu Sholat Jum\'at',
      'ms': 'Waktu Solat Juma\'ah',
      'ru': 'Время молитвы Джумаа',
      'tr': 'Cuma Namazı Vakti',
      'ur': 'نماز جمعہ کا وقت',
    },
    'vhqcd18d': {
      'en': 'Second Jumaa',
      'ar': 'جمعة الخطيب',
      'bn': 'জুমার খতীব',
      'es': 'Jumaa Khateeb',
      'fa': 'جمعه خطیب',
      'fr': 'Joumaa Khateeb',
      'hi': 'जुमा खतीब',
      'id': 'Jumaa Khatieb',
      'ms': 'Jumaa Khateeb',
      'ru': 'Джумаа Хатиб',
      'tr': 'Jumaa Khateeb',
      'ur': 'خطیب جمعہ',
    },
    '59otgxdl': {
      'en': 'Home',
      'ar': 'بيت',
      'bn': 'বাড়ি',
      'es': 'Hogar',
      'fa': 'صفحه اصلی',
      'fr': 'Maison',
      'hi': 'घर',
      'id': 'Rumah',
      'ms': 'Rumah',
      'ru': 'Дом',
      'tr': 'Ev',
      'ur': 'گھر',
    },
  },
  // createEpisode
  {
    'egrd6i3p': {
      'en': 'Create Episode',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'bhe7nzt4': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '4z8yse9l': {
      'en': 'Episode Number',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '9b4yx6v0': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '9aftduim': {
      'en': 'Title',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '7jnq0p8i': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'ip9wpn6y': {
      'en': 'Link',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '5pf8xwed': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'i6w1a4pt': {
      'en': 'Description',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '2odenl6s': {
      'en': 'Make more',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '4eay4ie5': {
      'en': 'Done',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '3hl4mq7f': {
      'en': 'Home',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
  },
  // createEvents
  {
    'crvrm8ot': {
      'en': 'Create Event',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '5hsc8zwd': {
      'en': 'Tab 1',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '438beavo': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'rlkum9vs': {
      'en': 'Event Title',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'nldusucw': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'y9e58oke': {
      'en': 'Location',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '4tk5hk7l': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'hyqj6fa0': {
      'en': 'Point Value',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'k1pof6cb': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '4pmawwe1': {
      'en': 'Attendance Code',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'qkbdmrf4': {
      'en': 'Continue',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '9goyv1n2': {
      'en': 'Tab 2',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'xn49o8pu': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '008o68te': {
      'en': 'Event Description',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '31yk4bgx': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'tb6ov474': {
      'en': 'Mandatory Link (If Applicable)',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '3jea0wea': {
      'en': ' Lecture',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'jyjy8jje': {
      'en': 'Workshop',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    't1ujmhbs': {
      'en': 'Fundraiser',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'a5qjnay5': {
      'en': 'Seminar',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'n6dvydjc': {
      'en': 'Select Type',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'kn0gqnds': {
      'en': 'Search...',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'j2fdd3pt': {
      'en': 'Back',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'xba7rf49': {
      'en': 'Publish',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '87wwbamh': {
      'en': 'Home',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
  },
  // createAnnouncement
  {
    'ocno4mmq': {
      'en': 'Create Announcement',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'k577hxb8': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    't3l1soeg': {
      'en': 'Announcement Title',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'e2vrf4i7': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'g6hc3xzf': {
      'en': 'Message',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '681r9j08': {
      'en': 'Everyone',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'xaz31yk4': {
      'en': 'Brothers',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'n13jfcm0': {
      'en': 'Sisters',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '1ew2gb3q': {
      'en': 'Hadith of the Week',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'nu4my501': {
      'en': 'Target Audience',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'wve8jmp9': {
      'en': 'Search...',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'dnwm42hj': {
      'en': 'Publish',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '26bnnsfs': {
      'en': 'Home',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
  },
  // createJobs
  {
    '5jgsn3mp': {
      'en': 'Create Job',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'carxmdal': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '3t4c9b1p': {
      'en': 'Title',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'b5576bq4': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'ki8q2k24': {
      'en': 'Description',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '7peaj44j': {
      'en': 'Done',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'xgs0sf5b': {
      'en': 'Home',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
  },
  // createMedia
  {
    'z6tmow5j': {
      'en': 'Create Media',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '84ooumic': {
      'en': 'Movie',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'mu3cyor9': {
      'en': 'Series',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '498q0v0a': {
      'en': 'Select Type',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'l9bn45x4': {
      'en': 'Search...',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'kzx9pc0g': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '3x7x1rox': {
      'en': 'Title',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'mmh8y1su': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'i6095lzv': {
      'en': 'Link',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'cd6cpp75': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'acba37t5': {
      'en': 'Description',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'g7zs6xxt': {
      'en': 'Everyone',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'k9zhvw7w': {
      'en': 'Brothers',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'vre2xq24': {
      'en': 'Sisters',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'xohmz9em': {
      'en': 'Target Audience',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'wdxofopr': {
      'en': 'Search...',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'xb8g51t6': {
      'en': 'Continue',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'x5icc679': {
      'en': 'Home',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
  },
  // editEpisode
  {
    'b9ub1vvq': {
      'en': 'Edit Episode',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'abmc2gjg': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'awj7sdjo': {
      'en': 'Episode Number',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '6mg3gwwn': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'fzlmmve2': {
      'en': 'Title',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'mx2poqot': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'rbpdq290': {
      'en': 'Link',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '5qam9kpq': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'po2lksh5': {
      'en': 'Description',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'mj9inetp': {
      'en': 'Done',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'acpz2r6k': {
      'en': 'Home',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
  },
  // editJobs
  {
    '2vhfshph': {
      'en': 'Edit Job',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '2p4vn97m': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'p0yvi0fi': {
      'en': 'Title',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'ukzp4e86': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '9p9du3rz': {
      'en': 'Description',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'nrijluo1': {
      'en': 'Done',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'zgwhw6l8': {
      'en': 'Delete Job',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'q2ec86ns': {
      'en': 'Applicants',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '29n7b8i1': {
      'en': 'Home',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
  },
  // editMedia
  {
    'dopqrn5z': {
      'en': 'Edit Media',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '6gfcilgo': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'y1u95nq0': {
      'en': 'Title',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'g9juj72w': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'i1sexw0q': {
      'en': 'Link',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'kv7brp3p': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'w22fk6iz': {
      'en': 'Description',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '7j3exqlm': {
      'en': 'Everyone',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'v1h99g0z': {
      'en': 'Brothers',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'npr7pcjk': {
      'en': 'Sisters',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '81bntvf0': {
      'en': 'Target Audience',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '1as2vgn7': {
      'en': 'Search...',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'te4645qd': {
      'en': 'Continue',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'frl7bhy2': {
      'en': 'Delete Media',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '0hxg0sle': {
      'en': 'Manage Episodes',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'p6qu8mwj': {
      'en': 'Create Episode',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '0lyv7cqf': {
      'en': 'Home',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
  },
  // manageJobs
  {
    'bh6rad9d': {
      'en': 'Manage Jobs',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '2s50jwgc': {
      'en': 'Create Job',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'n39accoq': {
      'en': 'Job Expired',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '0g3nfxvc': {
      'en': 'Home',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
  },
  // manageMedia
  {
    'nms5jcrz': {
      'en': 'Manage Media',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'p4g26ffc': {
      'en': 'Create Media',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'ixbxjqh4': {
      'en': 'Home',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
  },
  // singleApplicant
  {
    'lynrv5oj': {
      'en': 'Applicants',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'yzuq8yt1': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '2jhwjqha': {
      'en': 'Name',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'okwf61oj': {
      'en': 'Resume',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '8yuygrsl': {
      'en': 'View Resume',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'nor5tgzw': {
      'en': 'Contact Via Email',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'ov41yptd': {
      'en': 'Home',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
  },
  // Events
  {
    'lqcj8eik': {
      'en': 'SCMCC Events',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'ut9rwvha': {
      'en': 'Home',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
  },
  // singleEvent
  {
    '4lg74htb': {
      'en': 'Home',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
  },
  // EventPage
  {
    '224dff2w': {
      'en': 'You have Registered for this Event',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '8lxvpdzy': {
      'en': 'Home',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
  },
  // leaderboard
  {
    'n2sf7rl4': {
      'en': 'Back',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'l45tc30v': {
      'en': 'Leaderboard',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'vytby7lz': {
      'en': 'Home',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
  },
  // resources
  {
    '296dbljp': {
      'en': 'Resources',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'mevud7sc': {
      'en': 'Home',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
  },
  // createResource
  {
    'i69x4tcm': {
      'en': 'Create Resource',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    't5ok097f': {
      'en': 'Upload Thumbnail',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'fy9d82q6': {
      'en': 'Upload Resource',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '1egucvtx': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'o8lcfqu3': {
      'en': 'Title',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'g85e3isq': {
      'en': 'Continue',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'kshn9zud': {
      'en': 'Home',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
  },
  // manageEvents
  {
    'a4nfhwfs': {
      'en': 'Manage Events',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'kwimsffq': {
      'en': 'Create Event',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'bx3yp6x3': {
      'en': 'Event Ended',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'ea2xszko': {
      'en': 'Home',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
  },
  // editEvent
  {
    '2g3a84fv': {
      'en': 'Edit Event',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'hjmnxakq': {
      'en': 'Tab 1',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'd9xqhjli': {
      'en': 'Name',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'yhzpypce': {
      'en': 'Event Title',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'hk2m1x4o': {
      'en': 'Location',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'qv1z8xpv': {
      'en': 'Location',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'lfb0aqj7': {
      'en': 'Points',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    's51ekkm3': {
      'en': 'Point Value',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'jxefwieg': {
      'en': 'Code',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'eccc0u7k': {
      'en': 'Attendance Code',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'ju54qm7r': {
      'en': 'Continue',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'jhivfar8': {
      'en': 'Tab 2',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '5fc4j7fz': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'vhth8ctd': {
      'en': 'Event Description',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'tx9a0xka': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '49va365u': {
      'en': 'Mandatory Link (If Applicable)',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '7xhjkc75': {
      'en': ' Lecture',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '3ufpnxek': {
      'en': 'Workshop',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'hz8z935v': {
      'en': 'Fundraiser',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'jyconp4e': {
      'en': 'Seminar',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '2u2x4rbv': {
      'en': 'Select Type',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'ca36gga4': {
      'en': 'Search...',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'lz4n5q0p': {
      'en': 'Back',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'paudvjhg': {
      'en': 'Publish',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'ak07mdyq': {
      'en': 'Delete Event',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'k84jdjmf': {
      'en': 'Home',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
  },
  // community
  {
    'o9ymdlqt': {
      'en': 'Community',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '860skup2': {
      'en': 'Posts',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'cixb6h5p': {
      'en': 'Jobs',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '7myo0fy3': {
      'en': 'Coming Soon',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'th4xbiz1': {
      'en': 'Food',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'lnm8psex': {
      'en': 'Coming Soon',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '6e7g6no4': {
      'en': 'Coming Soon',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'q0683wvr': {
      'en': 'Coming Soon',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'rbnyjytm': {
      'en': 'Coming Soon',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'ud1h4xds': {
      'en': 'Store',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'nnkd8ddr': {
      'en': 'Coming Soon',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '2yyljvbx': {
      'en': 'Coming Soon',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '3581ibah': {
      'en': 'Promos',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'wvyme1ra': {
      'en': 'Coming Soon',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'f793kjvg': {
      'en': 'Recent Announcements',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '32o3ipqq': {
      'en': 'Posts',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'v61ufkgc': {
      'en': 'Home',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
  },
  // create
  {
    'drehg8m4': {
      'en': 'Post',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'ricn4itt': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'lww9rb72': {
      'en': 'Title',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'aolv4slq': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '14jv8d20': {
      'en': 'Enter Text',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'oh89xpf3': {
      'en': 'Option One',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '2m51gbbu': {
      'en': 'Option Two',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'ojyp9h7m': {
      'en': 'Option Three',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'bf2i16bg': {
      'en': '-',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'bd1a4q2j': {
      'en': 'Option Four',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '6oz6qf2t': {
      'en': '-',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '9tue88v3': {
      'en': 'Add More',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '5bckxr5t': {
      'en': 'Home',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
  },
  // PostsPage
  {
    'zg7cy8xc': {
      'en': 'Posts',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'tubb6k8e': {
      'en': 'Home',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
  },
  // Threads
  {
    'ngycr7f7': {
      'en': 'Posts',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'iu1z6s49': {
      'en': 'Home',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
  },
  // sendPushNotif
  {
    '2dh1vz69': {
      'en': 'Send Push Notification',
      'ar': 'إرسال إشعار الدفع',
      'bn': 'পুশ বিজ্ঞপ্তি পাঠান',
      'es': 'Enviar notificación push',
      'fa': 'ارسال Push Notification',
      'fr': 'Envoyer une notification push',
      'hi': 'पुश सूचना भेजें',
      'id': 'Kirim Pemberitahuan Push',
      'ms': 'Hantar Pemberitahuan Tolak',
      'ru': 'Отправить push-уведомление',
      'tr': 'Anlık Bildirim Gönder',
      'ur': 'پش نوٹیفکیشن بھیجیں۔',
    },
    'kv1cnh5b': {
      'en': 'Type message...',
      'ar': 'اكتب الرسالة...',
      'bn': 'বার্তা টাইপ করুন...',
      'es': 'Escribe mensaje...',
      'fa': 'تایپ پیام...',
      'fr': 'Tapez un message...',
      'hi': 'संदेश टाइप करें...',
      'id': 'Ketik pesan...',
      'ms': 'Taip mesej...',
      'ru': 'Введите сообщение...',
      'tr': 'Mesaj yazın...',
      'ur': 'پیغام ٹائپ کریں...',
    },
    '3k5kljo1': {
      'en': 'Launch Notification',
      'ar': 'إطلاق الإخطار',
      'bn': 'বিজ্ঞপ্তি চালু করুন',
      'es': 'Notificación de lanzamiento',
      'fa': 'اعلان را راه اندازی کنید',
      'fr': 'Notification de lancement',
      'hi': 'अधिसूचना लॉन्च करें',
      'id': 'Luncurkan Pemberitahuan',
      'ms': 'Pelancaran Pemberitahuan',
      'ru': 'Уведомление о запуске',
      'tr': 'Bildirimi Başlat',
      'ur': 'نوٹیفکیشن لانچ کریں۔',
    },
  },
  // post
  {
    't7amw52z': {
      'en': 'View Comments',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
  },
  // areYouSure
  {
    'njzk7sn0': {
      'en': 'Account Deletion',
      'ar': 'تعديل المنشور',
      'bn': 'পোস্ট সম্পাদনা করুন',
      'es': 'Editar post',
      'fa': 'ویرایش پست',
      'fr': 'Modifier le message',
      'hi': 'संपादित पोस्ट',
      'id': 'Sunting Posting',
      'ms': 'Edit Catatan',
      'ru': 'Редактировать пост',
      'tr': 'Gönderiyi düzenle',
      'ur': 'پوسٹ میں ترمیم کریں۔',
    },
    'jjs8x0u1': {
      'en':
          'Are you sure that you would like to delete your account? It is permanent and undoable.',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'o9zk2dhb': {
      'en': 'Confirm',
      'ar': 'يتأكد',
      'bn': 'নিশ্চিত করুন',
      'es': 'Confirmar',
      'fa': 'تایید',
      'fr': 'Confirmer',
      'hi': 'पुष्टि करना',
      'id': 'Mengonfirmasi',
      'ms': 'sahkan',
      'ru': 'Подтверждать',
      'tr': 'Onaylamak',
      'ur': 'تصدیق کریں۔',
    },
    'sfkjgcdw': {
      'en': 'Go Back',
      'ar': 'يتأكد',
      'bn': 'নিশ্চিত করুন',
      'es': 'Confirmar',
      'fa': 'تایید',
      'fr': 'Confirmer',
      'hi': 'पुष्टि करना',
      'id': 'Mengonfirmasi',
      'ms': 'sahkan',
      'ru': 'Подтверждать',
      'tr': 'Onaylamak',
      'ur': 'تصدیق کریں۔',
    },
  },
  // editProfile
  {
    'gyno3fvn': {
      'en': 'Edit Profile',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '8t1u04dr': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'w8cbsh5e': {
      'en': 'Username',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'huj2ct3c': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '9a4n3wfi': {
      'en': 'Email',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'wjpw3gg1': {
      'en': 'Male',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'yy62vhfo': {
      'en': 'Female',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '920n7rfa': {
      'en': 'Select your Gender',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'h4mss4sf': {
      'en': 'Search...',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
  },
  // Event
  {
    'gw9ixv4u': {
      'en': 'You Are Registered',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'gaw8e2nr': {
      'en': 'Event Concluded',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '1v8moxw4': {
      'en': 'Learn More',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'z6pv6ume': {
      'en': 'Register',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'unqgx9fm': {
      'en': 'Unregister',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
  },
  // EventAttendance
  {
    'kl4oqgc7': {
      'en': 'Please enter the code',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'vcdi18qc': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'gfz78i2l': {
      'en': 'Code',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'nijorh1e': {
      'en': 'Incorrect Code',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'x63tblwj': {
      'en': 'Welcome!',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
  },
  // comments
  {
    '71pvhvxo': {
      'en': 'Comments',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'jz32cwvd': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'lrsim5fw': {
      'en': 'Comment',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
  },
  // thread
  {
    'bzvk5uhk': {
      'en': 'Summary',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'ievzhmjc': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '08h3rlct': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'ow3ssmuu': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'qd78k6o1': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
  },
  // hashtags
  {
    'tf1z62yn': {
      'en': 'Hashtags',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
  },
  // linkMenu
  {
    '79i148am': {
      'en': 'Link',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '97thtfhj': {
      'en': 'You are about to follow a link to the following address:',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'qyjjaoi6': {
      'en': 'Dismiss',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'kx3ex0ru': {
      'en': 'Confirm',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
  },
  // BeautifyText
  {
    'lof6shm7': {
      'en': 'Beautified Text',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
  },
  // Miscellaneous
  {
    'u1dxyn3o': {
      'en':
          'In order to upload your profile picture, this app requires permission to access your camera',
      'ar':
          'من أجل تحميل صورة ملفك الشخصي، يتطلب هذا التطبيق إذنًا للوصول إلى الكاميرا',
      'bn':
          'আপনার প্রোফাইল ছবি আপলোড করার জন্য, এই অ্যাপটির আপনার ক্যামেরা অ্যাক্সেস করার অনুমতি প্রয়োজন',
      'es':
          'Para cargar su foto de perfil, esta aplicación requiere permiso para acceder a su cámara',
      'fa':
          'برای آپلود عکس نمایه شما، این برنامه برای دسترسی به دوربین شما نیاز به مجوز دارد',
      'fr':
          'Afin de télécharger votre photo de profil, cette application nécessite l\'autorisation d\'accéder à votre appareil photo.',
      'hi':
          'आपकी प्रोफ़ाइल तस्वीर अपलोड करने के लिए, इस ऐप को आपके कैमरे तक पहुंचने की अनुमति की आवश्यकता होती है',
      'id':
          'Untuk mengunggah gambar profil Anda, aplikasi ini memerlukan izin untuk mengakses kamera Anda',
      'ms':
          'Untuk memuat naik gambar profil anda, apl ini memerlukan kebenaran untuk mengakses kamera anda',
      'ru':
          'Чтобы загрузить изображение вашего профиля, этому приложению требуется разрешение на доступ к вашей камере.',
      'tr':
          'Profil resminizi yüklemek için bu uygulamanın kameranıza erişim iznine ihtiyacı var',
      'ur':
          'آپ کی پروفائل تصویر اپ لوڈ کرنے کے لیے، اس ایپ کو آپ کے کیمرے تک رسائی کی اجازت درکار ہے۔',
    },
    '32zpqd7c': {
      'en':
          'In order to upload your profile picture, this app requires permission to access your gallery',
      'ar':
          'من أجل تحميل صورة ملفك الشخصي، يتطلب هذا التطبيق إذنًا للوصول إلى معرض الصور الخاص بك',
      'bn':
          'আপনার প্রোফাইল ছবি আপলোড করার জন্য, এই অ্যাপটির আপনার গ্যালারি অ্যাক্সেস করার অনুমতি প্রয়োজন',
      'es':
          'Para cargar tu foto de perfil, esta aplicación requiere permiso para acceder a tu galería.',
      'fa':
          'برای آپلود عکس نمایه شما، این برنامه برای دسترسی به گالری شما به مجوز نیاز دارد',
      'fr':
          'Afin de télécharger votre photo de profil, cette application nécessite l\'autorisation d\'accéder à votre galerie',
      'hi':
          'अपनी प्रोफ़ाइल तस्वीर अपलोड करने के लिए, इस ऐप को आपकी गैलरी तक पहुंचने की अनुमति की आवश्यकता होती है',
      'id':
          'Untuk mengunggah gambar profil Anda, aplikasi ini memerlukan izin untuk mengakses galeri Anda',
      'ms':
          'Untuk memuat naik gambar profil anda, aplikasi ini memerlukan kebenaran untuk mengakses galeri anda',
      'ru':
          'Чтобы загрузить изображение вашего профиля, этому приложению требуется разрешение на доступ к вашей галерее.',
      'tr':
          'Profil resminizi yüklemek için bu uygulamanın galerinize erişim iznine ihtiyacı var',
      'ur':
          'آپ کی پروفائل تصویر اپ لوڈ کرنے کے لیے، اس ایپ کو آپ کی گیلری تک رسائی کی اجازت درکار ہے۔',
    },
    '65a4xb4w': {
      'en': 'In order to get notifications, this app requires your permission',
      'ar': 'للحصول على إشعارات، يتطلب هذا التطبيق إذنًا منك',
      'bn': 'বিজ্ঞপ্তি পেতে, এই অ্যাপ্লিকেশন আপনার অনুমতি প্রয়োজন',
      'es': 'Para recibir notificaciones, esta aplicación requiere su permiso',
      'fa': 'برای دریافت اعلان‌ها، این برنامه به اجازه شما نیاز دارد',
      'fr':
          'Afin de recevoir des notifications, cette application nécessite votre autorisation',
      'hi': 'सूचनाएं प्राप्त करने के लिए, इस ऐप को आपकी अनुमति की आवश्यकता है',
      'id': 'Untuk mendapatkan notifikasi, aplikasi ini memerlukan izin Anda',
      'ms':
          'Untuk mendapatkan pemberitahuan, apl ini memerlukan kebenaran anda',
      'ru':
          'Чтобы получать уведомления, этому приложению требуется ваше разрешение',
      'tr': 'Bu uygulamanın bildirim alabilmesi için izniniz gerekiyor',
      'ur': 'اطلاعات حاصل کرنے کے لیے، اس ایپ کو آپ کی اجازت درکار ہے۔',
    },
    'iwx7c0rj': {
      'en': 'For any audio recordings, the Microphone is necessary.',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'q9p4lc06': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'sb7caewr': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'to2kok4c': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'x07bdy6w': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '65o350zh': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'vfx5xe38': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'o1f87sdj': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'l62fc6jy': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'mki7pawf': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    't4oudipw': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'bhlskru9': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'cz49wvc2': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'ovdrf02l': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'lkj3vzkl': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'x86pcpgb': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'yoydjaal': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'p8d1crg9': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'alnw3lmp': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'hurzfmjz': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '9i96wst5': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'rbktfjkk': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'yfn7s54x': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'mtmd5un0': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    '6l4sms1w': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
    'ygfrhc7f': {
      'en': '',
      'ar': '',
      'bn': '',
      'es': '',
      'fa': '',
      'fr': '',
      'hi': '',
      'id': '',
      'ms': '',
      'ru': '',
      'tr': '',
      'ur': '',
    },
  },
].reduce((a, b) => a..addAll(b));
